### ISSUE TITLE
Use Ace code editor

### ISSUE THREAD

**Issue by alexschneider** [dartlab/dartlab#1]
It's rather difficult to edit code without syntax highlighting. 

[Ace](http://ace.c9.io/) has support for syntax highlighting for dart, css, and html, and they have [Dart bindings](https://pub.dartlang.org/packages/ace)

**Comment by ggirou** [comment]
Actually I'm working on a version with [Codemirror](http://codemirror.net).
Have a look to https://github.com/dartlab/dartlab/tree/dev_codemirror

Ace seems interesting and I'll give it a try.

**Comment by alexschneider** [comment]
To be completely honest, I’m happy with any form of syntax highlighting. Ace is what initially comes to mind when I think of code editors, but codemirror looks cool too. Do you have a demo up anywhere?

From: Guillaume Girou
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎12‎:‎33‎ ‎PM
To: dartlab/dartlab
Cc: Alexander Schneider

Actually I'm working on a version with Codemirror.
Have a look to https://github.com/dartlab/dartlab/tree/dev_codemirror

Ace seems interesting and I'll give it a try.

**Comment by ggirou** [comment]
[Demo](http://dartlab.org/codemirror-element/simple_example.html) and [sources](https://github.com/dartlab/codemirror-element) of codemirror-element :)

**Comment by ggirou** [comment]
And a running [DartLab](http://dev.dartlab.org/dev_codemirror/#9da4a11449128fc52638) with Codemirror :)

**Comment by ggirou** [comment]
Now on [darlab.org](http://dartlab.org/#9da4a11449128fc52638)!
