### ISSUE TITLE
potential problems with setInnerHtml

### ISSUE THREAD

**Issue by devoncarew** [dartlab/dartlab#8]
This line uses `setInnerHtml`:

https://github.com/dartlab/dartlab/blob/master/lib/src/gist_client.dart#L57

You may want to use it with a permissive validator, like here: https://github.com/dart-lang/dart-pad/blob/master/lib/src/gists.dart#L27 and definied here: https://github.com/dart-lang/dart-pad/blob/master/lib/src/util.dart#L24

**Comment by devoncarew** [comment]
Otherwise, I've seen setInnerHtml strip nodes/attributes out of the DOM tree for safety, which isn't really desired here...

**Comment by ggirou** [comment]
Thanks @devoncarew!
Do you have examples of nodes or attributes that setInnerHtml strips?

**Comment by devoncarew** [comment]
Yup, here's an example:

http://dartlab.org/#b51ea7c04322042b582a
